// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using helseProgram.Data;

#nullable disable

namespace helseProgram.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915010112_AddMedicationRelationships")]
    partial class AddMedicationRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("helseProgram.Modeller.MedikamentAdministrering", b =>
                {
                    b.Property<int>("MedikamentAdministreringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdministreringsMetode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministreringsType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Dose")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndeTid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enhet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MedikamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PasientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimSesjonsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("TEXT");

                    b.HasKey("MedikamentAdministreringId");

                    b.HasIndex("MedikamentId");

                    b.HasIndex("PasientId");

                    b.HasIndex("SimSesjonsId");

                    b.ToTable("MedikamentAdministrering");
                });

            modelBuilder.Entity("helseProgram.Modeller.Medikamenter", b =>
                {
                    b.Property<int>("MedikamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedikamentNavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MedikamentId");

                    b.ToTable("Medikamenter");
                });

            modelBuilder.Entity("helseProgram.Modeller.PasientInfo", b =>
                {
                    b.Property<int>("PasientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fodselsdag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PasientVekt")
                        .HasColumnType("INTEGER");

                    b.HasKey("PasientId");

                    b.ToTable("PasientInfo");
                });

            modelBuilder.Entity("helseProgram.Modeller.SimSesjon", b =>
                {
                    b.Property<int>("SimSesjonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndingsTid")
                        .HasColumnType("TEXT");

                    b.Property<string>("SesjonsNavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("TEXT");

                    b.HasKey("SimSesjonsId");

                    b.ToTable("SimSesjon");
                });

            modelBuilder.Entity("helseProgram.Modeller.MedikamentAdministrering", b =>
                {
                    b.HasOne("helseProgram.Modeller.Medikamenter", "Medikament")
                        .WithMany()
                        .HasForeignKey("MedikamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("helseProgram.Modeller.PasientInfo", "Pasient")
                        .WithMany()
                        .HasForeignKey("PasientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("helseProgram.Modeller.SimSesjon", "SimSesjon")
                        .WithMany()
                        .HasForeignKey("SimSesjonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medikament");

                    b.Navigation("Pasient");

                    b.Navigation("SimSesjon");
                });
#pragma warning restore 612, 618
        }
    }
}
